### ISSUE TITLE
Migrate Project to the Camunda Community Hub?

### ISSUE THREAD

**Issue by celanthe** [camunda-community-hub/camunda-external-task-client-python3#42]
Hello! I hope today finds you well! My name is Rin Oliver, and I'm a Technical Community Builder at Camunda. I'm opening this issue today to ask if you might be interested in migrating this extension over to the [Camunda Community Hub](https://github.com/camunda-community-hub/community)?

We'd love to hear your feedback on how we might improve the overall community extension development process for maintainers and contributors moving forward, and learn more about what you'd like to see from this initiative in the future.

If migrating this extension something you'd be interested in, I can send you the instructions for doing so via email, or whatever communication method works best for you. If you are for any reason no longer able to maintain this extension, if it is migrated to the Hub I would be more than happy to add a [lifecycle badge](https://github.com/camunda-community-hub/community/blob/main/extension-lifecycle.md) to it indicating that the project is in need of a new maintainer.

I'm also more than happy to schedule a call and talk over this in more detail if that would be preferable to you, for whenever best suits your schedule over the next few weeks.

Thank you so much for your time. I look forward to hearing from you.

**Comment by yogeshrnaik** [comment]
@celanthe 
I will be happy to migrate this project to Camunda Community Hub.

**Comment by celanthe** [comment]
Hi @yogeshrnaik! That's fantastic news. I've sent you an invite to become a Member of the Community Hub GitHub Organization. From there, you should be able to follow the [Getting Started](https://github.com/camunda-community-hub/community#getting-started) guide in the README, starting with https://github.com/camunda-community-hub/community#transferring-a-repository-in-your-personal-github-account. :) 

If you run into any issues, or have any questions, please don't hesitate to reach out. I am happy to help!

Best,
Rin

**Comment by celanthe** [comment]
Hi @yogeshrnaik! I hope today finds you well. I just wanted to circle back on this! :) if you need a new invitation to join the Community Hub, I'll be more than happy to send you one! I look forward to having this extension in the Community Hub, and thank you again for your wonderful contributions to Camunda!

**Comment by yogeshrnaik** [comment]
@celanthe I have created https://github.com/yogeshrnaik/camunda-external-task-client-python3/issues/51 for initiating the transfer. Please let me know if I need to do anything else?

**Comment by celanthe** [comment]
Hi @yogeshrnaik! That's fantastic, I've replied to you with next steps over on #51. We look forward to having this extension in the Community Hub! :)

**Comment by yogeshrnaik** [comment]
@celanthe
Repository is transferred to Camunda Community Hub.
