### ISSUE TITLE
Transfer yogeshrnaik/camunda-external-task-client-python3 into the Camunda Community Hub

### ISSUE THREAD

**Issue by yogeshrnaik** [camunda-community-hub/camunda-external-task-client-python3#51]
@celanthe

**Comment by celanthe** [comment]
Hi there @yogeshrnaik! As you're now a member of the Camunda Community Hub, you should be able to transfer the repository into the Community Hub by following these instructions: https://github.com/camunda-community-hub/community#transferring-a-repository-in-your-personal-github-account. :)

If you run into any issues, or have any questions, please don't hesitate to reach out. I am happy to help!

**Comment by yogeshrnaik** [comment]
@celanthe 
I have transferred the repository to Camunda Community Hub.
