### ISSUE TITLE
Worker  is not counting Down Retries and tasks is starting with retries = None

### ISSUE THREAD

**Issue by adilson-neotel** [camunda-community-hub/camunda-external-task-client-python3#53]
Hy community

First of all thanks for this good lib I using that a lot.
But for now  I experiencing a error.
I coded a Simple worker,  but it is not capable of fail a task, when the task is complete it is OK, but when task fail I cant fail the task on Camunda engine.

my Simple worker
```

#configuration for the Client
default_config = {
    "maxTasks": 100,
    "lockDuration": 10000,
    "asyncResponseTimeout": 5000,
    "retries": 0,
    "maxRetries": 3,
    "retryTimeout": 5000,
    "sleepSeconds": 30
}
```
```

def handle_task(task: ExternalTask) -> TaskResult:
    """
    This task handler is the hub to get task from camunda bpm-engine and switch to a bpcore task
    """

    logger.info(F"starting task: {task}")

    try:
        print (F"=====Task arrived ----------\n {task}\n ------------------------------\n")
        print (F"=====Properties ----------\n {task._context}\n ------------------------------\n")
        
        #here I do my things returning  a result object
        result = call.my.things()


        
        
        if result.status == "SUCCESS":
            print( f"Completing:{result.status}" )
            return task.complete(result.result)
        elif result.status == "FAILURE":

            try:
                print( f"failed ... :{result.result}" )
                x = task.failure(error_message="task failed",error_details="task failed forced",max_retries=1, retry_timeout=10 )
                print( f"\n---My call to failure is done ... :{task._context}----\n" )

            except (Exception) as e:
                print (F"Why my call Failed : ...{e}-------\n")


    except (Exception) as e:
        logger.error(f"ERROR_ON_EXCECUTE TASK: {e}", extra=task)
        

if __name__ == '__main__':

        ExternalTaskWorker( worker_id="2", config=default_config ).subscribe( "network", handle_task )
`
```
When I  run my code
I can check that:
first:
The task arrive with no retries property:

`{'activityId': 'run_discovery', 'activityInstanceId': 'run_discovery:4ec0150e-f6d5-11eb-a3c0-0242ac170003', 'errorMessage': None, 'errorDetails': None, 'executionId': '4ec0150d-f6d5-11eb-a3c0-0242ac170003', 'id': '4ec0150f-f6d5-11eb-a3c0-0242ac170003', 'lockExpirationTime': '2021-08-06T16:52:12.657+0000', 'processDefinitionId': 'BPDiscovery:3:cad9c151-f6d4-11eb-a3c0-0242ac170003', 'processDefinitionKey': 'BPDiscovery', 'processDefinitionVersionTag': None, 'processInstanceId': '4ebc1d65-f6d5-11eb-a3c0-0242ac170003', 'retries': None, 'suspended': False, 'workerId': '2', 'topicName': 'network', 'tenantId': None, 'variables': {'options': {'type': 'String', 'value': '-T4 -sV -A  -PS', 'valueInfo': {}}, 'target': {'type': 'String', 'value': '192.168.10.36', 'valueInfo': {}}}, 'priority': 0, 'businessKey': None, 'extensionProperties': {}}
`
Then my code raise a exception and it print 
failed and the result
After call task.failure
it prints 
`{'activityId': 'run_discovery', 'activityInstanceId': 'run_discovery:4ec0150e-f6d5-11eb-a3c0-0242ac170003', 'errorMessage': None, 'errorDetails': None, 'executionId': '4ec0150d-f6d5-11eb-a3c0-0242ac170003', 'id': '4ec0150f-f6d5-11eb-a3c0-0242ac170003', 'lockExpirationTime': '2021-08-06T16:59:43.919+0000', 'processDefinitionId': 'BPDiscovery:3:cad9c151-f6d4-11eb-a3c0-0242ac170003', 'processDefinitionKey': 'BPDiscovery', 'processDefinitionVersionTag': None, 'processInstanceId': '4ebc1d65-f6d5-11eb-a3c0-0242ac170003', 'retries': None, 'suspended': False, 'workerId': '2', 'topicName': 'network', 'tenantId': None, 'variables': {'options': {'type': 'String', 'value': '-T4 -sV -A  -PS', 'valueInfo': {}}, 'target': {'type': 'String', 'value': '192.168.10.36', 'valueInfo': {}}}, 'priority': 0, 'businessKey': None, 'extensionProperties': {}}`
That is:
the call to task.failure its ok, but not work.

After thart de worker print :

`ERROR:root:[WORKER_ID:2][TOPIC:network][TASK_ID:4ec0150f-f6d5-11eb-a3c0-0242ac170003] error when executing task: <class 'AttributeError'> : 'NoneType' object has no attribute 'get_task'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/camunda/external_task/external_task_worker.py", line 73, in _execute_task
    self.executor.execute_task(task, action)
  File "/usr/local/lib/python3.9/site-packages/camunda/external_task/external_task_executor.py", line 21, in execute_task
    self._handle_task_result(task_result)
  File "/usr/local/lib/python3.9/site-packages/camunda/external_task/external_task_executor.py", line 25, in _handle_task_result
    task = task_result.get_task()
AttributeError: 'NoneType' object has no attribute 'get_task'
`

And retry, retry forever !!! and the task was never finished

**Comment by adilson-neotel** [comment]
After my rubber duck say me that it will my failure call was without the return

**Comment by yogeshrnaik** [comment]
> After my rubber duck say me that it will my failure call was without the return

@adilson-neotel 
I am closing this issue based on your comments.
