### ISSUE TITLE
REST API Authentication

### ISSUE THREAD

**Issue by svenrr** [camunda-community-hub/camunda-external-task-client-python3#55]
Hey, 
does anyone have an idea to integrate the REST API basic authentication?

**Comment by yogeshrnaik** [comment]
@svenrr 
I believe latest version supports REST API basic auth.
Use this https://github.com/camunda-community-hub/camunda-external-task-client-python3/blob/master/docker-compose-auth.yml to bring up the service with REST API auth and test.
I have not tested but you can test and let me know if this does not work.

See examples here:
https://github.com/camunda-community-hub/camunda-external-task-client-python3/tree/master/examples/examples_auth_basic
