### ISSUE TITLE
Update of package in pypi

### ISSUE THREAD

**Issue by mstuebner** [camunda-community-hub/camunda-external-task-client-python3#70]
HI there,
we would like to use the Auth Rest as we need Auth in our prod environment, so is there any plan when a new package will show up in pypi (as we are forced to live from that source)?

Is there any release intervall for these community hub repositories?

br Matthias

**Comment by yogeshrnaik** [comment]
@mstuebner 4.1.0 is released on Pypi.org
https://pypi.org/manage/project/camunda-external-task-client-python3/release/4.1.0/
