### ISSUE TITLE
Change IP Adress of Camunda run

### ISSUE THREAD

**Issue by leanderpfeiffer** [camunda-community-hub/camunda-external-task-client-python3#80]
Hey there, 

I've been trying to get the task client, as well as Camunda, running in docker containers.
It's mostly working, but I can't figure out, how I can change the URL, which the task client is trying to reach.

I know, that it's possible to configure an engine_base_url when creating a ExternalClient instance, but I can't figure out, how this Client can be included when subscribing to a topic.

Help would be highly appreciated

**Comment by bachi76** [comment]
This works for me:

```
    camunda_url = "http://localhost:9080/engine-rest"

    executor = ThreadPoolExecutor(max_workers=3)

    executor.submit(ExternalTaskWorker(worker_id=0, base_url=camunda_url, config=default_config).subscribe, "step1", handle_step1)
...
```

**Comment by leanderpfeiffer** [comment]
Hey @bachi76,

thank you for the response! Worked for me as well :) just couldn't find the parameter anywhere in the documentation :/
